services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: innovation_db
    environment:
      POSTGRES_DB: innovation_db
      POSTGRES_USER: innovation_user
      POSTGRES_PASSWORD: innovation_pw
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: innovation_app
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./fonts:/app/fonts
    environment:
      PYTHONPATH: /app
      DATABASE_URL: postgresql://innovation_user:innovation_pw@db:5432/innovation_db
    ports:
      - "8501:8501"

  adminer:
    build:
      context: .
      dockerfile: Dockerfile.adminer-dark
    container_name: innovation_adminer
    depends_on:
      - db
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_DB: innovation_db
    ports:
      - "8080:8080"

volumes:
  db_data:
